### ISSUE TITLE
Pagination support?

### ISSUE THREAD

**Issue by Enovale** [hughbris/grav-theme-landed#8]
Would be nice to be able to use Pagination out of the box with this theme, as it seems to me that you can't (maybe i'm wrong, I'm new to Grav)

**Comment by hughbris** [comment]
So sorry for the slow response, I usually try to answer much more quickly! This one slipped through for one reason or another.

This is just a Grav port of the [theme designed and provided by HTML5UP](https://html5up.net/landed) and it does not appear to come with a paginator. Also, I am a coder and not a designer, so I would be a terrible person to come up with one.

(Of course it is possible, you can produce any markup with Grav Twig templates!)

Did you end up creating a paginator with this theme and are you happy to share that code if you did? I will gladly incorporate it.

**Comment by hughbris** [comment]
Assuming the answer to my question is 'no'
